[package]
name = "pedagog-k8s"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
pedagog-core = { path = "../core" }
kube = { workspace = true }
k8s-openapi = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
